//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diziler
    {
        public int dizi_id { get; set; }
        public string diziAd { get; set; }
        public Nullable<int> diziSezonsayisi { get; set; }
        public string IMDB { get; set; }
        public string diziAciklama { get; set; }
        public string diziVideo { get; set; }
        public string diziYonetmen { get; set; }
        public string diziFoto { get; set; }
        public string diziOyuncu { get; set; }
        public string diziOyuncuFoto { get; set; }
        public string diziYonetmenFoto { get; set; }
    }
}
