//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_Oyuncu
    {
        public int film_oyuncu_id { get; set; }
        public int film_id { get; set; }
        public int oyuncu_id { get; set; }
    }
}
