//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        public int film_id { get; set; }
        public string filmAd { get; set; }
        public string filmSuresi { get; set; }
        public string IMDB { get; set; }
        public string filmAciklama { get; set; }
        public string filmVideo { get; set; }
        public string filmYonetmen { get; set; }
        public string filmFoto { get; set; }
        public string filmOyuncu { get; set; }
        public string filmYonetmenFoto { get; set; }
        public string filmOyuncuFoto { get; set; }
    }
}
