//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmDiziEntities : DbContext
    {
        public FilmDiziEntities()
            : base("name=FilmDiziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dizi_Kategori> Dizi_Kategori { get; set; }
        public virtual DbSet<Dizi_Oyuncu> Dizi_Oyuncu { get; set; }
        public virtual DbSet<Diziler> Diziler { get; set; }
        public virtual DbSet<Film_Kategori> Film_Kategori { get; set; }
        public virtual DbSet<Film_Oyuncu> Film_Oyuncu { get; set; }
        public virtual DbSet<Filmler> Filmler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Oyuncular> Oyuncular { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<Yonetmenler> Yonetmenler { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
    }
}
