//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int uye_id { get; set; }
        public string uyeAd { get; set; }
        public string uyeSoyad { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public string uyeEmail { get; set; }
        public string uyePassword { get; set; }
        public byte[] fotograf { get; set; }
        public string uyeYetki { get; set; }
    }
}
